### ISSUE TITLE
as without parameter fails with exception

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [SapphireProject/sapphire-2#17]
```
def putchar()
    as

putchar()
```

This code is throwing following exception:

```
% python3.6 sapphire libsph.sph libsph.asm && bfasm < libsph.asm > libsph.b && bfi libsph.b
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "sapphire/__main__.py", line 29, in <module>
    parser.parse(code)
  File "sapphire/__parser__.py", line 318, in parse
    if tokens[1][0] != '"' or tokens[1][-1] != '"':
IndexError: list index out of range
```

Instead of gracefully presenting it to the user.

**Comment by maviek** [comment]
```
as
 ^
error: invalid syntax
```

Fixed with #54 (v2.0.5)
