### ISSUE TITLE
Can't place quote inside quote

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [SapphireProject/sapphire-2#24]
```

if "test"
    as "\""

```

Fails with exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "sapphire/__main__.py", line 29, in <module>
    parser.parse(code)
  File "sapphire/__parser__.py", line 276, in parse
    tokens = lex(line)
  File "sapphire/__lexer__.py", line 40, in lex
    for token in lexer.tokenize(line):
  File "/usr/local/lib/python3.6/dist-packages/sly/lex.py", line 424, in tokenize
    tok = self.error(tok)
  File "/usr/local/lib/python3.6/dist-packages/sly/lex.py", line 439, in error
    raise LexError(f'Illegal character {t.value[0]!r} at index {self.index}', t.value, self.index)
sly.lex.LexError: Illegal character '"' at index 10
```

**Comment by maviek** [comment]
Use "\x22".

**Comment by KrzysztofSzewczyk** [comment]
Nope. Add escape sequence for quotes.

**Comment by maviek** [comment]
#77 Escape sequence for quotes have been added.
