### ISSUE TITLE
Dumps out an error while attempting to run.

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [SapphireProject/sapphire-2#3]
```sh 
0 root@SzewczykPC [7:57pm] guwno % python3 sapphire
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "sapphire/__main__.py", line 1, in <module>
    from __parser__ import *
  File "sapphire/__parser__.py", line 1, in <module>
    from __lexer__ import *
  File "sapphire/__lexer__.py", line 1, in <module>
    from sly import Lexer
  File "/usr/local/lib/python3.5/dist-packages/sly/__init__.py", line 2, in <module>
    from .lex import *
  File "/usr/local/lib/python3.5/dist-packages/sly/lex.py", line 79
    return f'Token(type={self.type!r}, value={self.value!r}, lineno={self.lineno}, index={self.index})'

  ^
SyntaxError: invalid syntax
```

The error appears in the library. Could you drop installation script to repository? `pip install sly` is scraping broken version of library.

**Comment by maviek** [comment]
Use **Python 3.6.x**
