### ISSUE TITLE
global is bailing out with exception when an expression is passed as parameter.

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [SapphireProject/sapphire-2#41]
```
global while(1)
    as "out 48"
```

Bails out like such:

```
% python3.6 sapphire libsph.sph libsph.asm
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "sapphire/__main__.py", line 29, in <module>
    parser.parse(code)
  File "sapphire/__parser__.py", line 327, in parse
    n = self.func + '.' + v
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by maviek** [comment]
```
error: expected identifier at token 2 (line 4)
```
No, it doesn't.
